#!/usr/bin/perl
#
# This script executes ColyseusQuake on a remote machine which has the
# image generated by MakeImage.pl installed.
#
# The first host will be used as the master host and as the bootstrap host.
#

use strict;
use conf;
use Net::hostent;
use Socket;
use Getopt::Std;
require "inc.pl";

our $USER = "ashu";
our $PROG = "mono ./OctoSim/OctoSim.exe";
our $common_args = "-w Hetero.wl -t 10000 -maxu 5 -sbw 6000 -fsize 819200 -b 2048 -jr 100 -j 10";

sub RunCommand 
{
    my ($cmd, $outdir) = @_;

    $outdir = "data/$outdir";
    chdir($TOPDIR);
    psystem("mkdir -p $outdir"); 
    $OUTPUT_REDIR = "$outdir/OUTPUT.log";
    psystem("$cmd -o $outdir/default.out");
    psystem("gzip $outdir/default.out.*");
}

sub RunPolicies 
{
    my ($cmd, $outdir) = @_;
    $outdir = "data/$outdir";
    
    chdir($TOPDIR);
    my %policies = ('lr', '', 
	    'random', '-r 400',
	    'permute', '-permutations');

    foreach my $policy (keys %policies) {	 
	psystem("mkdir -p $outdir/policy-$policy");
	$OUTPUT_REDIR = "$outdir/policy-$policy/OUTPUT.log";
	psystem("$cmd $policies{$policy} -o $outdir/policy-$policy/default.out");
	psystem("gzip $outdir/policy-$policy/default.out.*");
    }
}
## Run the IBW expt 
{
    my $ibw_args = "-bw '6000:3000:0.33 1500:400:0.33 784:128:0.34' -fec 1 -d 40 -ibw";
    rsystem_opts(0, 1, $USER, "iris-d-02", \&RunCommand, "$PROG $common_args $ibw_args", "ibw");
}

## Run the LR, Random, Permute expts
{
    my $args_fmt = "-bw '6000:3000:0.33 1500:400:0.33 784:128:0.34' -fec 1 -d %d ";
    my %hash = ('3', 'iris-d-03', 
	        '5', 'iris-d-04', 
		'10', 'iris-d-05');

    foreach my $d (keys %hash) {
	rsystem_opts(0, 1, $USER, $hash{$d}, \&RunPolicies, "$PROG $common_args " . sprintf($args_fmt, $d), "d-$d");
    }
}

## Run the LR, Random, Permute expts with Homogeneous things
{
    our $common_args = "-w Homog.wl -t 10000 -maxu 5 -sbw 6000 -fsize 819200 -b 2048 -jr 100 -j 10";
    my $args_fmt = "-bw '1500:400:1.0' -fec 1 -d %d ";
    my %hash = ('3', 'iris-d-06', 
	        '5', 'iris-d-07', 
		'10', 'iris-d-08');

    foreach my $d (keys %hash) {
	rsystem_opts(0, 1, $USER, $hash{$d}, \&RunPolicies, "$PROG $common_args " . sprintf($args_fmt, $d), "d-$d");
    }
}

